version: "3.2"

services:
  arangodb:
    container_name: satakolkyt-arangodb
    image: arangodb/arangodb
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGO_STORAGE_ENGINE=rocksdb
    volumes:
      - ./arangodb_volume/:/var/lib/arangodb3/
    env_file:
      - .env
