version: "3.3"

services:
  app:
    container_name: expresssatakolkyt
    restart: always
    networks:
      - front
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - ./:/app
    links:
      - arangodb
    env_file:
      - .env
  nginx:
    image: nginx:latest
    restart: always
    container_name: production_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/www/certbot/:/var/www/certbot/
    ports:
      - 80:80
      - 443:443
    links:
      - arangodb
      - app

  arangodb:
    container_name: satakolkytarangodb3
    image: arangodb/arangodb
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGO_STORAGE_ENGINE=rocksdb
    env_file:
      - .env
