version: "3.3"

services:
  app:
    container_name: express-satakolkyt
    restart: always
    build: ./
    ports:
      - "8089:8089"
    volumes:
      - .:/app
    links:
      - arangodb
    environment:
      - PORT=8089
      - DB_USER=root
      - DB_PASS=root
      - DB_URL=http://satakolkytarangodb3:8529
      - DB_NAME=satakolkyt
      - FRONT_USER=test
      - FRONT_PASS=test

  arangodb:
    container_name: satakolkytarangodb3
    image: arangodb/arangodb
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGO_STORAGE_ENGINE=rocksdb
    volumes:
      - ./arangodb_volume/:/var/lib/arangodb3/
    env_file:
      - .env
